# -*- coding: utf-8 -*-
"""Midterm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8tqqRIfMjB6yeN-Jwy7lAAcqE2hlm64
"""

import folium
import requests
import time
import matplotlib.pyplot as plt
import base64
from io import BytesIO
from IPython.display import display, clear_output
from folium.plugins import MarkerCluster, HeatMap

# API Key từ OpenWeatherMap
API_KEY = "38c3c0e48aaee85c6a3dd868b8f3244a"

# Danh sách các thành phố lớn trên thế giới
CITIES = [
    "New York", "Los Angeles", "London", "Paris", "Berlin", "Moscow",
    "Tokyo", "Seoul", "Beijing", "Bangkok", "Dubai", "Singapore",
    "Sydney", "Mexico City", "Buenos Aires", "São Paulo", "Cairo",
    "Johannesburg", "Mumbai", "Istanbul", "Toronto", "Chicago", "Jakarta"
]

# Hàm tạo biểu đồ tốc độ gió
def create_wind_chart(wind_speeds, timestamps):
    plt.figure(figsize=(4, 2))
    plt.plot(timestamps, wind_speeds, marker="o", linestyle="-", color="blue", label="Wind Speed (km/h)")
    plt.xticks(rotation=45, fontsize=6)
    plt.yticks(fontsize=6)
    plt.xlabel("Time", fontsize=8)
    plt.ylabel("Wind Speed (km/h)", fontsize=8)
    plt.title("Wind Speed Trend", fontsize=10)
    plt.legend(fontsize=6)
    plt.grid()

    # Chuyển biểu đồ thành ảnh base64
    buffer = BytesIO()
    plt.savefig(buffer, format="png", dpi=100)
    buffer.seek(0)
    encoded_img = base64.b64encode(buffer.getvalue()).decode()
    plt.close()

    return f'<img src="data:image/png;base64,{encoded_img}" width="200">'

# Lưu trữ dữ liệu gió theo thời gian
city_wind_data = {city: {"timestamps": [], "wind_speeds": []} for city in CITIES}

while True:
    try:
        # Xóa màn hình trước khi cập nhật
        clear_output(wait=True)

        # Tạo bản đồ toàn cầu
        m = folium.Map(location=[20.0, 0.0], zoom_start=2)  # Zoom xa hơn để xem toàn thế giới
        marker_cluster = MarkerCluster().add_to(m)
        heat_data = []  # Dữ liệu cho Heatmap

        for city in CITIES:
            # Lấy dữ liệu từ OpenWeatherMap
            URL = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
            response = requests.get(URL)
            data = response.json()

            if response.status_code != 200:
                print(f"Lỗi khi lấy dữ liệu cho {city}: {data}")
                continue

            wind_speed_kph = data["wind"]["speed"] * 3.6  # Chuyển từ m/s sang km/h
            wind_deg = data["wind"]["deg"]  # Hướng gió (độ)
            lat = data["coord"]["lat"]
            lon = data["coord"]["lon"]

            # Lưu dữ liệu gió
            city_wind_data[city]["timestamps"].append(time.strftime("%H:%M:%S"))
            city_wind_data[city]["wind_speeds"].append(wind_speed_kph)

            # Giữ lại tối đa 10 giá trị gần nhất
            if len(city_wind_data[city]["timestamps"]) > 10:
                city_wind_data[city]["timestamps"].pop(0)
                city_wind_data[city]["wind_speeds"].pop(0)

            # Tạo biểu đồ tốc độ gió
            wind_chart = create_wind_chart(
                city_wind_data[city]["wind_speeds"],
                city_wind_data[city]["timestamps"]
            )

            # Xác định hướng gió
            wind_direction = ""
            if 337.5 <= wind_deg or wind_deg < 22.5:
                wind_direction = "⬆️ North"
            elif 22.5 <= wind_deg < 67.5:
                wind_direction = "↗️ North-East"
            elif 67.5 <= wind_deg < 112.5:
                wind_direction = "➡️ East"
            elif 112.5 <= wind_deg < 157.5:
                wind_direction = "↘️ South-East"
            elif 157.5 <= wind_deg < 202.5:
                wind_direction = "⬇️ South"
            elif 202.5 <= wind_deg < 247.5:
                wind_direction = "↙️ South-West"
            elif 247.5 <= wind_deg < 292.5:
                wind_direction = "⬅️ West"
            elif 292.5 <= wind_deg < 337.5:
                wind_direction = "↖️ North-West"

            # Tạo nội dung popup với dữ liệu gió
            popup_info = folium.Popup(
                folium.IFrame(
                    f"<b>{city}</b><br>"
                    f"🌬️ Wind Speed: {wind_speed_kph:.1f} km/h<br>"
                    f"🧭 Wind Direction: {wind_direction}<br>"
                    f"{wind_chart}",
                    width=250,
                    height=300
                ),
                max_width=300
            )

            # Thêm dữ liệu vào Heatmap (tốc độ gió)
            heat_data.append([lat, lon, wind_speed_kph])

            # Đổi màu biểu tượng dựa vào tốc độ gió
            if wind_speed_kph < 10:
                icon_color = "blue"
            elif wind_speed_kph < 20:
                icon_color = "green"
            elif wind_speed_kph < 30:
                icon_color = "orange"
            else:
                icon_color = "red"

            # Thêm marker vào bản đồ
            folium.Marker(
                location=[lat, lon],
                popup=popup_info,
                icon=folium.Icon(color=icon_color),
            ).add_to(marker_cluster)

        # Thêm lớp Heatmap vào bản đồ
        HeatMap(heat_data, radius=25, blur=15).add_to(m)

        # Hiển thị bản đồ
        display(m)

        time.sleep(30)  # Cập nhật sau mỗi 30 giây

    except Exception as e:
        print("Error:", e)
        break
